exclude: 'node_modules|venv|.git'
default_stages: [ commit, push ]
fail_fast: true

default_language_version:
    python: python3.9.10

repos:
    -   repo: https://github.com/pycqa/pylint
        rev: v2.13.5
        hooks:
            -   id: pylint
                exclude: "[a-zA-Z]*/(migrations)/(.)*"
                args:
                    - --errors-only
                    - --rcfile=.pylintrc
                    - --disable=django-not-available
                    - --disable=import-error
                additional_dependencies: [ pylint_django,
                                           pylint_celery, ]

    -   repo: https://github.com/PyCQA/flake8
        rev: 4.0.1
        hooks:
            -   id: flake8
                args: [ "--config=setup.cfg" ]
                additional_dependencies: [ "flake8-bugbear",
                                           "flake8-comprehensions",
                                           "flake8-mutable",
                                           "flake8-print",
                                           "flake8-simplify",
                                           "flake8-isort" ]

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.1.0
        hooks:
            -   id: check-added-large-files
            -   id: check-ast
            -   id: check-byte-order-marker
            -   id: check-docstring-first
            -   id: check-executables-have-shebangs
            -   id: check-json
            -   id: check-merge-conflict
            -   id: check-symlinks
            -   id: check-vcs-permalinks
            -   id: check-xml
            -   id: check-yaml
            -   id: debug-statements
            -   id: detect-private-key
            -   id: end-of-file-fixer
            -   id: forbid-new-submodules
            -   id: mixed-line-ending
            -   id: trailing-whitespace
            -   id: check-case-conflict

    -   repo: https://github.com/psf/black
        rev: 22.3.0
        hooks:
            -   id: black

    -   repo: https://github.com/PyCQA/isort
        rev: 5.10.1
        hooks:
            -   id: isort

    -   repo: https://github.com/pycqa/bandit
        rev: 1.7.0
        hooks:
            -   id: bandit
                args: [ "-iii", "-ll" ]

    -   repo: https://github.com/asottile/pyupgrade
        rev: v2.25.0
        hooks:
            -   id: pyupgrade
                args: [ "--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus" ]

    -   repo: https://github.com/asottile/seed-isort-config
        rev: v2.2.0
        hooks:
            -   id: seed-isort-config

    -   repo: local
        hooks:
            -   id: pytest-check
                name: pytest-check
                entry: pytest
                language: system
                pass_filenames: false
                always_run: true