# Generated by Django 4.0.5 on 2022-06-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alterec2request",
            name="instance_name",
            field=models.CharField(default="tezt", max_length=255),
            preserve_default=False,
        ),
    ]
