FROM python:3.9.7-slim-buster

RUN apt-get update && apt-get install -y gcc python3-dev libpq-dev

# Install requirements
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# Custom working directory
WORKDIR /app
